### ISSUE TITLE
Readonly TextField border dimension inconsitency

### ISSUE THREAD

**Issue by mrgreywater** [parttio/parity-theme#5]
The height of the border of a TextField seems to change visually by 2px depending on if the field is readonly or not. A readonly TextField appears smaller which looks weird in a Form. This can be seen in the Parity-Theme Live Demo. The style also doesn't match the GS Design, I think the GS Read Only state behaviour looks worse though. See https://design.gs.com/components/input

![image](https://github.com/parttio/parity-theme/assets/2902403/9c51b260-4318-497c-b170-1f62791f7a96)

**Comment by mrgreywater** [comment]
Something like this would fix it

```css
*[readonly]::part(input-field) {
    border: 1px dashed var(--lumo-contrast-30pct);
}

::part(input-field)::after {
    border: unset;
}
```
